name: Calendar Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  calendar-automation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Set up OAuth token
      run: |
        echo "${{ secrets.GOOGLE_OAUTH_TOKEN }}" | base64 -d > token.pickle

    - name: Run calendar automation
      env:
        PRIMARY_EMAIL: ${{ secrets.PRIMARY_EMAIL }}
        SECONDARY_EMAIL: ${{ secrets.SECONDARY_EMAIL }}
        TERTIARY_EMAIL: ${{ secrets.TERTIARY_EMAIL }}
      run: uv run scripts/calendar_automation.py
