name: Calendar Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  calendar-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Call Google Apps Script
      run: |
        # Get the web app URL from secrets
        WEBAPP_URL="${{ secrets.GOOGLE_APPS_SCRIPT_URL }}"

        if [ -z "$WEBAPP_URL" ]; then
          echo "❌ GOOGLE_APPS_SCRIPT_URL secret not set"
          exit 1
        fi

        echo "🔗 Calling Google Apps Script..."
        response=$(curl -s "$WEBAPP_URL")

        if [ $? -eq 0 ]; then
          echo "✅ Script executed successfully"
          echo "📊 Response: $response"
        else
          echo "❌ Failed to execute script"
          exit 1
        fi